export const newCompanyDataObject = {
  staticFields: [
    {
      key: 'name',
      name: 'Company name',
      description: 'Your company name',
      type: 'text',
      encryptable: false,
    },
    {
      key: 'purpose',
      name: 'Description',
      description: 'Truthful scope of business',
      type: 'text',
      encryptable: false,
    },
    {
      key: 'logoURL',
      name: 'Logo URL',
      description: 'URL to logo',
      type: 'text',
      encryptable: false,
    },
    {
      key: 'charterURL',
      name: 'Charter URL',
      type: 'text',
      encryptable: false,
    },
    {
      key: 'totalCapitalAmount',
      name: 'Capital Amount',
      description: 'Total capital amount',
      type: 'text',
      encryptable: false,
    },
    {
      key: 'totalCapitalCurrency',
      name: 'Capital Currency',
      description: 'Total capital currency',
      type: 'text',
      encryptable: false,
    },
    {
      key: 'numberOfShares',
      name: 'Number of Shares',
      description: 'Total number of shares',
      type: 'text',
      encryptable: false,
    },
    {
      key: 'companyType',
      name: 'Company Type',
      type: 'radio',
      encryptable: false,
    },
  ],
  dynamicFields: [
    {
      key: 'brandNames',
      display: 'List of brand names the company is doing business as',
      name: 'Brand Name',
      fields: [
        {
          key: 'name',
          name: 'Brand name',
          type: 'text',
          encryptable: true,
        },
      ],
      data: [
        [{
          key: 'name',
          display: 'Brand Name',
          isEncrypted: false,
        }],
      ],
    },
    {
      key: 'onlineAddresses',
      display: 'List of all online addresses',
      name: 'Online Address',
      fields: [
        {
          key: 'description',
          name: 'Description',
          display: 'Description of online address',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'url',
          name: 'URL',
          display: 'URL of online address',
          type: 'text',
          encryptable: true,
        },
      ],
      data: [
        [{
          key: 'description',
          display: 'Description of online address',
          isEncrypted: false,
        },
        {
          key: 'url',
          display: 'URL of online address',
          isEncrypted: false,
        }],
      ],
    },
    {
      key: 'contact',
      display: 'List of contacts',
      name: 'Contact info',
      fields: [
        {
          key: 'contact',
          name: 'Contact',
          type: 'text',
          encryptable: true,
        },
      ],
      data: [
        [{
          key: 'contact',
          display: 'Contact info (optional)',
          isEncrypted: false,
        }],
      ],
    },
    {
      key: 'physicalAddresses',
      display: 'List of all physical addresses',
      name: 'Physical Address',
      fields: [
        {
          key: 'description',
          name: 'Description',
          display: 'Description of physical address',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'street',
          name: 'Street',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'city',
          name: 'city',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'subdivision',
          name: 'Subdivision',
          display: 'Subdivision - state/province/emirate/oblast/etc',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'postalCode',
          name: 'Postal Code',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'country',
          name: 'Country',
          type: 'text',
          encryptable: true,
        },
      ],
      data: [],
    },
    {
      key: 'principals',
      display: 'List of owners (principals)',
      name: 'Owners',
      fields: [
        {
          key: 'walletAddress',
          name: 'Wallet',
          display: 'Liberland wallet address',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'name',
          name: 'Owner',
          display: 'Name of owner (principal)',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'passportNumber',
          name: 'Liberland ID',
          display: 'Liberland ID or Liberland passport number of owner (principal)',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'shares',
          name: 'Number of shares',
          display: 'Number of shares of owner (principal)',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'signingAbilityConditions',
          name: 'Notes',
          display: 'Conditions or notes',
          type: 'text',
          encryptable: true,
        },
      ],
      data: [
        [{
          key: 'walletAddress',
          display: 'Liberland wallet address',
          isEncrypted: false,
        },
        {
          key: 'name',
          display: 'Name of principal',
          isEncrypted: false,
        },
        {
          key: 'passportNumber',
          display: 'Passport number of principal',
          isEncrypted: false,
        },
        {
          key: 'shares',
          display: 'Number of shares of principal',
          isEncrypted: false,
        },
        {
          key: 'signingAbilityConditions',
          display: 'Conditions or notes',
          isEncrypted: false,
        }],
      ],
    },
    {
      key: 'shareholders',
      display: 'List of all shareholders',
      name: 'Shareholders',
      fields: [
        {
          key: 'walletAddress',
          name: 'Wallet',
          display: 'Liberland wallet address',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'name',
          name: 'Name',
          display: 'Name of shareholder',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'passportNumber',
          name: 'Liberland ID',
          display: 'Liberland ID or Liberland passport number of shareholder',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'shares',
          name: 'Number of shares',
          display: 'Number of shares of shareholder',
          type: 'text',
          encryptable: true,
        },
      ],
      data: [],
    },
    {
      key: 'UBOs',
      display: 'List of all Ultimate Beneficiaries',
      name: 'Beneficiaries',
      fields: [
        {
          key: 'walletAddress',
          name: 'Wallet',
          display: 'Liberland wallet address',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'name',
          name: 'Name',
          display: 'Name of Ultimate Beneficiary',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'passportNumber',
          name: 'Liberland ID',
          display: 'Liberland ID or Liberland passport number of Ultimate Beneficiary',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'signingAbility',
          name: 'Signing ability',
          display: 'Can be full or other',
          type: 'text',
          encryptable: true,
        },
        {
          key: 'signingAbilityConditions',
          name: 'Conditions',
          display: 'Any conditions on UBO signing ability. Must be in agreement',
          type: 'text',
          encryptable: true,
        },
      ],
      data: [],
    },
    {
      key: 'relevantContracts',
      display: 'List of relevant on-chain contract ids',
      name: 'Relevant on-chain Contracts',
      fields: [
        {
          key: 'contractId',
          name: 'Contract ID',
          type: 'text',
          encryptable: true,
        },
      ],
      data: [],
    },
    {
      key: 'relevantAssets',
      display: 'List of relevant on-chain asset ids)',
      name: 'Relevant on-chain Assets',
      fields: [
        {
          key: 'assetId',
          name: 'Asset ID',
          type: 'text',
          encryptable: true,
        },
      ],
      data: [],
    },
  ],
};
