export const GuidedStepEnum = {
  LOADING: 'LOADING',
  UNSUPPORTED_BROWSER: 'UNSUPPORTED_BROWSER',
  NO_WALLETS_AVAILABLE: 'NO_WALLETS_AVAILABLE',
  MISSING_WALLET: 'MISSING_WALLET',
  NO_CONNECTED_WALLET: 'NO_CONNECTED_WALLET',
};
